### ISSUE TITLE
Missing definition RtlAdjustPrivilege

### ISSUE THREAD

**Issue by dbyoung720** [diversenok/NtUtilsLibrary#4]
Missing definition RtlAdjustPrivilege
hope to add

**Comment by diversenok** [comment]
Hi. Thanks for the report.

I added a definition to the headers, but I don't think it's necessary to create a wrapper for it. When using the library, I suggest calling `NtxAdjustPrivilege` or `NtxAdjustPrivileges` because they provide more flexibility. Here are some tips on how to use them:

 - Besides ordinary handles, you can specify `NtCurrentProcessToken`, `NtCurrentThreadToken`, or `NtCurrentEffectiveToken`. The first two options correspond to setting the `Client` parameter of `RtlAdjustPrivilege` to False and True, respectively.
 - You can supply values from `TSeWellKnownPrivilege` enumeration, so you don't need to lookup a privilege LUID from its name.
 - Use `SE_PRIVILEGE_DISABLED`, `SE_PRIVILEGE_ENABLED`, or `SE_PRIVILEGE_REMOVED` to indicate the desired state.
 - To try without failing the function when the privilege is not available, set `IgnoreMissing` to True and then compare the result to `STATUS_NOT_ALL_ASSIGNED`. That provides functionality similar to `WasEnabled` of `RtlAdjustPrivilege`.

**Comment by dbyoung720** [comment]
OK. Thank!
